### ISSUE TITLE
Building OpenCV from source is a load for users: Ship docker container instead

### ISSUE THREAD

**Issue by krshrimali** [BuffetCodes/DCGAN-CelebA-PyTorch-CPP#7]
Building OpenCV from source isn't that straight forward. And it varies from system to system. Shipping docker container with OpenCV & PyTorch built from source might be a better idea.

Open to discussions.

cc: @HimanshuSinghGH

**Comment by HimanshuSinghGH** [comment]
The Dockerfile for the same has been created and added to the list of repositories.
